import type {RJPStudioStructurePackage,StudioValue} from './studioExchange'

const IFC_CHARS='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_$'
function hash32(s:string,seed=2166136261){let h=seed>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
export function stableIfcGuid(key:string){let out='';let a=hash32(key),b=hash32(key,0x9e3779b9),c=hash32(key,0x85ebca6b);for(let i=0;i<22;i++){const v=(a^((b<<((i%5)+1))>>>0)^c^i)>>>0;out+=IFC_CHARS[v%64];a=(Math.imul(a,1664525)+1013904223)>>>0;b=(Math.imul(b,1103515245)+12345)>>>0;c=(c^c<<13^c>>>17^c<<5)>>>0}return out}
const esc=(s:unknown)=>String(s??'').replace(/'/g,"''")
const fmt=(v:number)=>Number.isFinite(v)?Number(v.toFixed(6)).toString():'0'
const val=(v:StudioValue)=>typeof v==='number'?`IFCREAL(${fmt(v)})`:typeof v==='boolean'?`IFCBOOLEAN(${v?'.T.':'.F.'})`:`IFCLABEL('${esc(v)}')`

class W{n=1;lines:string[]=[];add(body:string){const id=this.n++;this.lines.push(`#${id}=${body};`);return id}}
function point(w:W,x:number,y:number,z:number){return w.add(`IFCCARTESIANPOINT((${fmt(x)},${fmt(y)},${fmt(z)}))`)}
function dir(w:W,x:number,y:number,z:number){return w.add(`IFCDIRECTION((${fmt(x)},${fmt(y)},${fmt(z)}))`)}
function placement(w:W,x:number,y:number,z:number,axis:[number,number,number]=[0,0,1],ref:[number,number,number]=[1,0,0]){const p=point(w,x,y,z),a=dir(w,...axis),r=dir(w,...ref),ax=w.add(`IFCAXIS2PLACEMENT3D(#${p},#${a},#${r})`);return w.add(`IFCLOCALPLACEMENT($,#${ax})`)}
function shape(w:W,L:number,Wd:number,H:number){const pos=point(w,0,0,0),axis=dir(w,0,0,1),ref=dir(w,1,0,0),ax=w.add(`IFCAXIS2PLACEMENT3D(#${pos},#${axis},#${ref})`),profile=w.add(`IFCRECTANGLEPROFILEDEF(.AREA.,$,#${ax},${fmt(Math.max(.02,L))},${fmt(Math.max(.02,Wd))})`),d=dir(w,0,0,1),solid=w.add(`IFCEXTRUDEDAREASOLID(#${profile},#${ax},#${d},${fmt(Math.max(.02,H))})`),rep=w.add(`IFCSHAPEREPRESENTATION($,'Body','SweptSolid',(#${solid}))`);return w.add(`IFCPRODUCTDEFINITIONSHAPE($,$,(#${rep}))`)}
function pset(w:W,owner:number,guid:string,name:string,props:Record<string,StudioValue>){const ids=Object.entries(props).filter(([,v])=>v!==undefined).map(([k,v])=>w.add(`IFCPROPERTYSINGLEVALUE('${esc(k)}',$,${val(v)},$)`));if(!ids.length)return;const ps=w.add(`IFCPROPERTYSET('${stableIfcGuid(guid+name)}',$,'${esc(name)}',$,(${ids.map(i=>`#${i}`).join(',')}))`);w.add(`IFCRELDEFINESBYPROPERTIES('${stableIfcGuid(guid+name+'rel')}',$,$,$,(#${owner}),#${ps})`)}

export function structureToIfc(p:RJPStudioStructurePackage){const w=new W();const projectGuid=stableIfcGuid(String(p.project.name||'SmartStruct Project'))
 const org=w.add(`IFCORGANIZATION($,'RJP Engineering',$,$,$)`),person=w.add(`IFCPERSON($,$,'RJP',$,$,$,$,$,$)`),pa=w.add(`IFCPERSONANDORGANIZATION(#${person},#${org},$)`),app=w.add(`IFCAPPLICATION(#${org},'116.1.3','SmartStruct RJP','SMARTSTRUCT_RJP')`),hist=w.add(`IFCOWNERHISTORY(#${pa},#${app},$,.ADDED.,$,$,$,0)`)
 const proj=w.add(`IFCPROJECT('${projectGuid}',#${hist},'${esc(p.project.name||'SmartStruct Project')}',$,$,$,$,$,$)`),sitePl=placement(w,0,0,0),site=w.add(`IFCSITE('${stableIfcGuid(projectGuid+'site')}',#${hist},'Site',$,$,#${sitePl},$,$,.ELEMENT.,$,$,$,$,$)`),bldPl=placement(w,0,0,0),bld=w.add(`IFCBUILDING('${stableIfcGuid(projectGuid+'building')}',#${hist},'Building',$,$,#${bldPl},$,$,.ELEMENT.,$,$,$)`)
 w.add(`IFCRELAGGREGATES('${stableIfcGuid(projectGuid+'siteRel')}',#${hist},$,$,#${proj},(#${site}))`);w.add(`IFCRELAGGREGATES('${stableIfcGuid(projectGuid+'bldRel')}',#${hist},$,$,#${site},(#${bld}))`)
 const els:number[]=[];const nodes=new Map(p.nodes.map(n=>[n.id,n]))
 for(const m of p.members){const a=nodes.get(m.a||-1),b=nodes.get(m.b||-1);const x1=a?.x||0,z1=a?.y||0,x2=b?.x??x1+Number(m.geometry.length||1),z2=b?.y??z1;const L=Math.hypot(x2-x1,z2-z1)||Number(m.geometry.length||1);const vertical=m.kind==='column'||Math.abs(x2-x1)<1e-7;const x=(x1+x2)/2,z=Math.min(z1,z2);const pl=placement(w,x,0,z);const sh=shape(w,vertical?.35:L,vertical?.45:.25,vertical?L:.5);const g=stableIfcGuid(`${projectGuid}:${m.id}`),cls=vertical?'IFCCOLUMN':'IFCBEAM',id=w.add(`${cls}('${g}',#${hist},'${esc(vertical?'Pilar ':'Viga ')}${esc(m.id)}',$,$,#${pl},#${sh},$,$)`);els.push(id);pset(w,id,g,'Pset_RJP_Identity',{RJP_Id:m.id,RJP_Type:m.kind,RJP_Source:'SmartStruct RJP'});pset(w,id,g,'Pset_RJP_Engineering',{...m.results,reinforcement:m.reinforcement??null,nodeA:m.a??null,nodeB:m.b??null});pset(w,id,g,'Pset_RJP_Geometry',{RJP_X:x,RJP_Y:0,RJP_Z:z,RJP_SizeX:vertical?.35:L,RJP_SizeY:vertical?.45:.25,RJP_SizeZ:vertical?L:.5,RJP_RotationZ:vertical?0:Math.atan2(z2-z1,x2-x1)});pset(w,id,g,'Pset_RJP_Material',{material:m.material?.name??null,family:m.material?.family??null,...m.material?.properties})}
 for(const f of p.foundations){const n=nodes.get(f.node),B=Number(f.geometry.B_m||1.5),L=Number(f.geometry.L_m||B),H=Number(f.geometry.h_m||.5),pl=placement(w,n?.x||0,0,-H),sh=shape(w,B,L,H),g=stableIfcGuid(`${projectGuid}:${f.id}`),id=w.add(`IFCFOOTING('${g}',#${hist},'Fundação ${esc(f.id)}',$,$,#${pl},#${sh},$,.PAD_FOOTING.)`);els.push(id);pset(w,id,g,'Pset_RJP_Identity',{RJP_Id:f.id,RJP_Type:f.kind,RJP_Source:'SmartStruct RJP'});pset(w,id,g,'Pset_RJP_Engineering',{...f.actions,...f.results,reinforcement:f.reinforcement??null,node:f.node});pset(w,id,g,'Pset_RJP_Geometry',{B_m:B,L_m:L,h_m:H,RJP_X:n?.x||0,RJP_Y:0,RJP_Z:-H/2,RJP_SizeX:B,RJP_SizeY:L,RJP_SizeZ:H,RJP_RotationZ:0})}
 if(els.length)w.add(`IFCRELCONTAINEDINSPATIALSTRUCTURE('${stableIfcGuid(projectGuid+'contains')}',#${hist},$,$,(${els.map(i=>`#${i}`).join(',')}),#${bld})`)
 pset(w,proj,projectGuid,'Pset_RJP_Project',{RJP_App:'SmartStruct RJP',RJP_Version:'116.1.3',RJP_ProjectName:String(p.project.name||''),RJP_Location:String(p.project.location||''),RJP_Floors:Number(p.project.floors||0),RJP_Bays:Number(p.project.bays||0),RJP_Bay_m:Number(p.project.bay||0),RJP_Storey_m:Number(p.project.storey||0)})
 return `ISO-10303-21;\nHEADER;\nFILE_DESCRIPTION(('ViewDefinition [CoordinationView_V2.0]'),'2;1');\nFILE_NAME('${esc(p.project.name||'SmartStruct')}.ifc','${new Date().toISOString()}',('RJP'),('RJP Engineering'),'SmartStruct RJP 116.1.3','SmartStruct RJP','');\nFILE_SCHEMA(('IFC4'));\nENDSEC;\nDATA;\n${w.lines.join('\n')}\nENDSEC;\nEND-ISO-10303-21;\n`}
export function downloadStructureIfc(p:RJPStudioStructurePackage,base='SmartStruct'){const blob=new Blob([structureToIfc(p)],{type:'application/x-step'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`${base.replace(/[^a-z0-9_-]+/gi,'_')||'SmartStruct'}_Estrutura.ifc`;a.click();URL.revokeObjectURL(u)}

export interface IfcProjectHint{name?:string;location?:string;floors?:number;bays?:number;bay?:number;storey?:number;counts:Record<string,number>}
function prop(text:string,key:string){const re=new RegExp(`IFCPROPERTYSINGLEVALUE\\('${key.replace(/[.*+?^${}()|[\\]\\]/g,'\\$&')}'[^;]*?(?:IFCLABEL\\('([^']*)'\\)|IFCREAL\\(([-+0-9.eE]+)\\)|IFCINTEGER\\(([-+0-9]+)\\))`,'i'),m=text.match(re);return m?.[1]??m?.[2]??m?.[3]}
export function inspectIfc(text:string):IfcProjectHint{const c:Record<string,number>={};for(const k of ['IFCBEAM','IFCCOLUMN','IFCSLAB','IFCWALL','IFCFOOTING','IFCPILE','IFCDOOR','IFCWINDOW'])c[k]=(text.match(new RegExp(`=${k}\\(`,'g'))||[]).length;return{name:prop(text,'RJP_ProjectName'),location:prop(text,'RJP_Location'),floors:Number(prop(text,'RJP_Floors'))||undefined,bays:Number(prop(text,'RJP_Bays'))||undefined,bay:Number(prop(text,'RJP_Bay_m'))||undefined,storey:Number(prop(text,'RJP_Storey_m'))||undefined,counts:c}}
